version: '2'

services:
  mysqla:
    container_name: mysqla
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
  mysqlb:
    container_name: mysqlb
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
  proxysql:
    container_name: proxysql
    image: dtestops/proxysql
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf

