#!/bin/bash

while [[ $# -gt 1 ]]
do
  key="$1"

  case $key in
    -h|--host)
      HOST="$2"
      shift # past argument
    ;;
    *)
            # unknown option
    ;;
  esac
  shift # past argument or value
done

case $HOST in
  proxysql)
    docker exec -it $HOST mysql -h 127.0.0.1 -P 6032 -u admin -p
  ;;
  mysqla|mysqlb|master|slave)
    docker exec -it $HOST mysql -h 127.0.0.1 -P 3306 -u root -p
  ;;
esac