#!/bin/bash

while [[ $# -gt 1 ]]
do
  key="$1"

  case $key in
    -h|--host)
      HOST="$2"
      shift # past argument
    ;;
    -u|--user)
      USER="$2"
      shift # past argument
    ;;
    *)
            # unknown option
    ;;
  esac
  shift # past argument or value
done

case $HOST in
  proxy-admin)
    docker exec -it proxysql mysql -h 127.0.0.1 -P 6032 -u admin -padmin
  ;;
  proxy-sql)
    docker exec -it proxysql mysql -h 127.0.0.1 -P 6033 -u $USER -pamsterdam
  ;;
  mysqla|mysqlb|master|slave)
    docker exec -it $HOST mysql -h 127.0.0.1 -P 3306 -u root -psecret
  ;;
esac